from tdr.tests.creation_composant_version                 import *
'''
from tdr.tests.creation_type                              import *
from tdr.tests.creation_etat                              import *
from tdr.tests.creation_client                            import *
from tdr.tests.creation_nature                            import *
from tdr.tests.creation_produit                           import *
from tdr.tests.suppression_type                           import *
from tdr.tests.creation_licence                           import *
from tdr.tests.suppression_etat                           import *
from tdr.tests.modification_etat                          import *
from tdr.tests.modification_type                          import *
from tdr.tests.suppression_client                         import *
from tdr.tests.suppression_nature                         import *
from tdr.tests.creation_composant                         import *
from tdr.tests.suppression_produit                        import *
from tdr.tests.suppression_licence                        import *
from tdr.tests.modification_client                        import *
from tdr.tests.modification_nature                        import *
from tdr.tests.modification_licence                       import *
from tdr.tests.modification_produit                       import *
from tdr.tests.suppression_composant                      import *
from tdr.tests.modification_composant                     import *
from tdr.tests.creation_produit_version                   import *
from tdr.tests.creation_version_logiciel                  import *
from tdr.tests.suppression_produit_version                import *
from tdr.tests.suppression_version_logiciel               import *
from tdr.tests.modification_produit_version               import *
from tdr.tests.suppression_composant_version              import *
from tdr.tests.modification_version_logiciel              import *
from tdr.tests.modification_composant_version             import *
from tdr.tests.creation_produit_version_composant_version import *
'''